spring:
  application:
    name: international-delivery
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
       default_schema: international-delivery
       dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres

server:
  port: 8462
