spring:
  application:
    name: international-delivery
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: international-delivery

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/international-delivery
    username: postgres
    password: R2-D2-F1-L1

server:
  port: 80
